apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-app-deployment
  labels:
    app: scale-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale-app
  template:
    metadata:
      labels:
        app: scale-app
    spec:
      containers:
        - name: scale-app-container
          image: shestera/scaletestapp
          resources:
            limits:
              memory: "30Mi"
          ports:
            - containerPort: 8080
